# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: gmx_MMPBSA Documentation test
site_url: https://valdes-tresanco-ms.github.io/mkdocs_versioning_test
site_author: Mario
site_description: >-
  (test) gmx_MMPBSA is a new tool based on AMBER's MMPBSA.py aiming to perform end-state free energy calculations with 
  GROMACS files

# Repository
repo_name: Valdes-Tresanco-MS/mkdocks_versioning_test
repo_url: https://github.com/Valdes-Tresanco-MS/mkdocks_versioning_test
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 - 2022 MS. and ME. Valdes Tresanco

# Configuration
theme:
  name: material
  logo: assets/logo_white_border.svg
  custom_dir: docs/overrides


  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
#    - navigation.indexes
    # - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
#    - navigation.tracking
    - search.highlight
#    - search.share
    - search.suggest
    # - header.autohide
    - toc.integrate

  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

#    - scheme: default
#      primary: black
#      accent: black
#      toggle:
#        icon: material/weather-sunny
#        name: Switch to dark mode
#    - scheme: slate
#      primary: black
#      accent: black
#      toggle:
#        icon: material/weather-night
#        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.svg
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
  - minify:
      minify_html: true

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Valdes-Tresanco-MS
  version:
    provider: mike

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Valdes-Tresanco-MS
      repo: gmx_MMPBSA
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Getting started: getting-started.md
    - Introduction: introduction.md
    - gmx_MMPBSA in a nutshell: summary.md
    - gmx_MMPBSA vs other programs: versus.md
    - Installation: installation.md
  - gmx_MMPBSA:
    - How gmx_MMPBSA works: howworks.md
    - Command-line: gmx_MMPBSA_command-line.md
    - Running gmx_MMPBSA: gmx_MMPBSA_running.md
    - The input file: input_file.md
    - The output file: output.md
    - Python API: api.md
  - gmx_MMPBSA_ana:
    - gmx_MMPBSA_ana: analyzer.md
    - Command-line: gmx_MMPBSA_ana_command-line.md
    - Running gmx_MMPBSA_ana: gmx_MMPBSA_ana_running.md
  - Examples:
    - Examples: examples/README.md
    - Systems:
      - Protein-protein: examples/Protein_protein/README.md
      - Protein-ligand: examples/Protein_ligand/ST/README.md
      - Protein-DNA: examples/Protein_DNA/README.md
      - Protein-glycan: examples/Protein_glycan/README.md
      - Membrane proteins: examples/Protein_membrane/README.md
      - Metalloprotein-peptide: examples/Metalloprotein_peptide/README.md
      - Multicomponent system: examples/Comp_receptor/README.md
      - COVID-19 related proteins:
          - Info: examples/COVID-19_related_proteins/README.md
          - Main protease: examples/COVID-19_related_proteins/Main_protease_7l5d/README.md
          - Papain-like protease: examples/COVID-19_related_proteins/Papain-like_protease_7koj/README.md
          - S1-ACE2 complex: examples/COVID-19_related_proteins/S1-ACE2_complex_7dmu/README.md
          - S1 RBD with antibody: examples/COVID-19_related_proteins/S1_RBD_with_antibody_6zlr/README.md
    - CHARMMff Support:
        - Protein-ligand: examples/Protein_ligand_CHARMMff/README.md
        - Protein-ligand complex embedded in membrane: examples/Protein_membrane_CHARMMff/README.md
        - Protein-ligand with LPH particles (ST): examples/Protein_ligand_LPH_atoms_CHARMMff/README.md
    - OPLSff Support:
        - Protein-protein: examples/OPLS/protein_protein/README.md
    - Analysis:
        - Single Trajectory Protocol: examples/Protein_ligand/ST/README.md
        - Multiple Trajectory Protocol: examples/Protein_ligand/MT/README.md
        - BFE calculations:
            - BFE calculation with GB: examples/Protein_ligand/ST/README.md
            - BFE calculation with Linear PB: examples/Linear_PB_solver/README.md
            - BFE calculation with NonLinear PB : examples/NonLinear_PB_solver/README.md
            - BFE calculation with 3D-RISM: examples/3D-RISM/README.md
        - Alanine scanning: examples/Alanine_scanning/README.md
        - Decomposition analysis: examples/Decomposition_analysis/README.md
        - Entropy calculations:
            - Interaction Entropy: examples/Entropy_calculations/Interaction_Entropy/README.md
            - nmode Entropy: examples/Entropy_calculations/nmode/README.md
            - C2 Entropy calculations: examples/Entropy_calculations/C2_Entropy/README.md
        - Stability calculations: examples/Stability/README.md
        - QM/MMGBSA: examples/QM_MMGBSA/README.md
    - Support for psf_dcd files:
        - Protein-protein: examples/psf_dcd/protein_protein/README.md
        - Protein-ligand: examples/psf_dcd/protein_ligand/README.md
        - Multicomponent system: examples/psf_dcd/multicomponent_system/README.md
    - gmx_MMPBSA_test: examples/gmx_MMPBSA_test.md
  - Help:
    - Help: Q&A/README.md
    - Installation: Q&A/installation.md
    - OS issues: Q&A/OS_issues.md
    - Calculations: Q&A/calculations.md
    - Info:
      - Changelog: changelog.md
      - Compatibility: compatibility.md
      - Private Policy: private_policy.md
  - Cite gmx_MMPBSA: cite_us.md

extra_css:
  - assets/stylesheets/termynal.css
  - assets/stylesheets/custom.css
extra_javascript:
  - assets/js/termynal.js
  - assets/js/custom.js
