name: documentation
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

env:
  PYTHON_VERSION: 3.x

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
           # Number of commits to fetch. 0 indicates all history. For mkdocs-git-revision-date-localized-plugin
           # Default: 1
           fetch-depth: 0

      - name: Set up Python runtime
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set release notes tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
            echo $RELEASE_VERSION
            echo ${{ env.RELEASE_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install mike
          pip install mkdocs-material
      - name: Deploy documentation
#        env:
#          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mike deploy --push --rebase --update-aliases dev
          mike deploy --push --update-aliases ${RELEASE_TAG_VERSION} latest
          
